group:
  repos: |
    mooseburgr/rss-to-ical
    mooseburgr/rss-to-ical-j
    mooseburgr/repository-settings-action
    mooseburgr/terraform-stuff
    mooseburgr/sync-ical-to-sportsengine
    mooseburgr/plex-utils
    mooseburgr/.github
    mooseburgr/plex-daddy
    mooseburgr/deno-sandbox
    mooseburgr/rust-sandbox
    mooseburgr/kmj-wtf-upptime
    mooseburgr/advent-2021
    mooseburgr/advent-2022
    mooseburgr/kotlin-sandbox
    mooseburgr/python-sandbox
    mooseburgr/mooseburgr.github.io
    mooseburgr/ical-party

  files:
    - source: .gitattributes
      replace: false
    - .github/CODEOWNERS
    - source: .github/settings.yml
      replace: false
    - source: .github/dependabot.yml
      replace: false
    - .github/mergify.yml
