group:
  repos: |
    mooseburgr/rss-to-ical-go	
    mooseburgr/rss-to-ical		
    mooseburgr/repository-settings-action		
    mooseburgr/terraform-stuff		
    mooseburgr/sync-ical-to-sportsengine	
    mooseburgr/plex-utils		
    mooseburgr/.github		
    mooseburgr/plex-daddy	
    mooseburgr/deno-sandbox	
    mooseburgr/rust-sandbox
    mooseburgr/kmj-wtf-upptime
    mooseburgr/advent-2021
    mooseburgr/advent-2022
    mooseburgr/docker-dev-env
    mooseburgr/code-with-quarkus
    mooseburgr/kotlin-sandbox
    mooseburgr/python-sandbox
    mooseburgr/mooseburgr.github.io

  files: 
    - .gitattributes
    - .github/CODEOWNERS
    - .github/settings.yml
    - .github/dependabot.yml
    - .github/mergify.yml
