group:
  repos: |
    mooseburgr/rss-to-ical
    mooseburgr/rss-to-ical-j		
    mooseburgr/repository-settings-action
    mooseburgr/repository-settings-action-ts
    mooseburgr/terraform-stuff		
    mooseburgr/sync-ical-to-sportsengine	
    mooseburgr/plex-utils		
    mooseburgr/.github		
    mooseburgr/plex-daddy	
    mooseburgr/deno-sandbox	
    mooseburgr/rust-sandbox
    mooseburgr/kmj-wtf-upptime
    mooseburgr/advent-2021
    mooseburgr/advent-2022
    mooseburgr/kotlin-sandbox
    mooseburgr/python-sandbox
    mooseburgr/mooseburgr.github.io

  files: 
    - source: .gitattributes
      replace: false
    - .github/CODEOWNERS
    - .github/settings.yml
    - source: .github/dependabot.yml
      replace: false
    - .github/mergify.yml
