name: sync files
on:
  push:
    branches:
      - main
  workflow_dispatch:
jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      # https://github.com/BetaHuhn/repo-file-sync-action
      - name: Run GitHub File Sync
        uses: BetaHuhn/repo-file-sync-action@v1
        with:
          GH_PAT: ${{ secrets.GH_PAT }}
          GIT_USERNAME: github-actions[bot]
          GIT_EMAIL: github-actions[bot]@users.noreply.github.com
          PR_LABELS: |
            sync
            ${{ github.repository_owner }}
          SKIP_PR: true # commit directly to main, YOLO
          ASSIGNEES: ${{ github.actor }}
